name: Go

on:
  push

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build Linux
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o uptimemonitor-linux-amd64 ./cmd/uptimemonitor

    - name: Build macOS
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o uptimemonitor-darwin-amd64 ./cmd/uptimemonitor

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          uptimemonitor-linux-amd64
          uptimemonitor-darwin-amd64

    - name: Test
      run: go run gotest.tools/gotestsum@latest --format testdox -- ./test